/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.BB.java.DBConnectionSample;

import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println("%s".formatted(System.getProperty("file.encoding")));
        System.out.println("✨✨✨");
        
        try (PrintWriter out = new PrintWriter(new OutputStreamWriter(new FileOutputStream("output.txt"), "UTF-8"))) {
        out.println("Id: 1, Name: Kiss József");
        out.println("Id: 2, Name: Nagy Ágnes");
        out.println("Id: 3, Name: Horváth István");
        out.println("Id: 4, Name: Kovács Jóska");
    } catch (IOException e) {
        e.printStackTrace();
}
        
        String url = "jdbc:mysql://localhost:3306/iskola?useUnicode=true&characterEncoding=UTF-8";
        String user = "root";
        String password = "Factoring123";

        try (Connection conn = DriverManager.getConnection(url, user, password)) {
            // Lekérdezés
            String sql = "SELECT * FROM tanulok";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);

            // Az eredmények kiírása output ablakba
            /*while (rs.next()) {
                int id = rs.getInt("id");
                String name = rs.getString("nev");   
                System.out.println("Id: " + id + ", Name: " + name);
            }*/
            // Az eredmények kiírása txt fileba
            try (PrintWriter out = new PrintWriter(new OutputStreamWriter(new FileOutputStream("output.txt"), "UTF-8"))) {            
                while (rs.next()) {
                    int id = rs.getInt("id");
                    String name = rs.getString("nev");
                    out.println("Id: " + id + ", Name: " + name);
                }
            } catch (IOException e) {
                e.printStackTrace();
        }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}
